# Generated by Django 5.0 on 2025-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
