# Generated by Django 5.2 on 2025-05-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userfollow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollow',
            new_name='UserFollows',
        ),
    ]
